### ISSUE TITLE
generateDoc.sh exits with make errors

### ISSUE THREAD

**Issue by serkonda7** [schutzwerk/CANalyzat0r#15]
**Describe the bug**
The shell script exits with following errors:
```
pi@pi:~/Documents/CANalyzat0r $ ./doc/generateDoc.sh html
make: *** Keine Regel, um „html“ zu erstellen.  Schluss.
make: *** Keine Regel, um „latexpdf“ zu erstellen.  Schluss.
```

**Expected behavior**
Generated pdf file.

**Comment by ps1337** [comment]
Hi!

Does

cd doc && ./generateDoc.sh work? 

-----Original Message-----
From: Lukas Neubert ***@***.***>
To: schutzwerk/CANalyzat0r ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Tue, 08 Feb 2022 13:07
Subject: [schutzwerk/CANalyzat0r] generateDoc.sh exits with make errors (Issue #15)

**Describe the bug**
The shell script exits with following errors:
```
***@***.***:~/Documents/CANalyzat0r $ ./doc/generateDoc.sh html
make: *** Keine Regel, um „html“ zu erstellen.  Schluss.
make: *** Keine Regel, um „latexpdf“ zu erstellen.  Schluss.
```

**Expected behavior**
Generated pdf file.


-- 
Reply to this email directly or view it on GitHub:
https://github.com/schutzwerk/CANalyzat0r/issues/15

**Comment by serkonda7** [comment]
It doesn't but I get a different error: `/usr/bin/python: No module named sphinx`

Maybe it's caused because I try to run it on an Raspberry Pi 3b+

**Comment by ps1337** [comment]
Alright, you need to install the python requirements first. There's an install_requirements.sh for this in the project root directory 

-----Original Message-----

**Comment by ps1337** [comment]
After that, you can use "pipenv shell" to run the tool and generate the docs. However, the intended way is to use docker since it bundles all requirements with the correct versions and so on

-----Original Message-----

**Comment by serkonda7** [comment]
Using docker fails due to arm architecture. Building the docker image as stated in #13 fails due to the following problem
```
Running command git clone --filter=blob:none --quiet https://github.com/hardbyte/python-can.git /root/.local/share/virtualenvs/pipenv-JNDGio94/src/can
  Running command git checkout -q 31c23bbd7c238e56f2c6a3b44c26d377a73ceb8c
  WARNING: Generating metadata for package can produced metadata for project name python-can. Fix your #egg=can fragments.
ERROR: Could not find a version that satisfies the requirement can (unavailable) (from versions: 0.0.0)
ERROR: No matching distribution found for can (unavailable)
```

I may just give up. Thanks for your fast responses :)
